In [107]:
import pandas as pd

df = pd.read_csv("./challenge-6-abalone.csv")

df.head()

   M  0.455  0.365  0.095   0.514  0.2245   0.101   0.15  15
0  M   0.35  0.265   0.09  0.2255  0.0995  0.0485   0.07   7
1  F   0.53   0.42  0.135   0.677  0.2565  0.1415   0.21   9
2  M   0.44  0.365  0.125   0.516  0.2155   0.114  0.155  10
3  I   0.33  0.255   0.08   0.205  0.0895  0.0395  0.055   7
4  I  0.425    0.3  0.095  0.3515   0.141  0.0775   0.12   8

In [108]:
columns_name = df.iloc[df.index[-1]].values  # 拉出末尾新行头
new_line = df.columns.values  # 拉出初始行头
# 删除行末
df = df.drop(df.index[-1])

# 更新行头
df.columns = columns_name

# 添加数据到行末
# 旧版本
# df = pd.DataFrame([new_line], columns=columns_name)._append(df, ignore_index=True)

# 新版本
df = pd.concat([df, pd.DataFrame([new_line], columns=columns_name)], ignore_index=True)

df.tail()

     Sex Length Diameter  ... Viscera weight Shell weight Rings
4172   M   0.59     0.44  ...         0.2145       0.2605    10
4173   M    0.6    0.475  ...         0.2875        0.308     9
4174   F  0.625    0.485  ...          0.261        0.296    10
4175   M   0.71    0.555  ...         0.3765        0.495    12
4176   M  0.455    0.365  ...          0.101         0.15    15

[5 rows x 9 columns]

In [109]:
### 方法二

# # 不要行头的方式读取数据，旧版本是header=-1
# dx = pd.read_csv("./challenge-6-abalone.csv", header=None)

# dx.head()
# # 行末更新到行头
# dx.columns = dx.iloc[-1].values
# # # 去除行末
# dx = dx.drop(dx.index[-1])
# dx.head()

In [110]:
# dx.tail()

In [111]:
# df["Sex"] = df["Sex"].replace("M", 0)
# df["Sex"] = df["Sex"].replace("F", 1)
# df["Sex"] = df["Sex"].replace("I", 2)
# df.head()

df["Sex"] = df.Sex.replace({"M": 0, "F": 1, "I": 2})
df.head()

C:\Users\91658\AppData\Local\Temp\ipykernel_31508\3008999447.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = df.Sex.replace({'M':0, 'F':1, 'I':2})

   Sex Length Diameter Height  ... Shucked weight Viscera weight Shell weight Rings
0    0   0.35    0.265   0.09  ...         0.0995         0.0485         0.07     7
1    1   0.53     0.42  0.135  ...         0.2565         0.1415         0.21     9
2    0   0.44    0.365  0.125  ...         0.2155          0.114        0.155    10
3    2   0.33    0.255   0.08  ...         0.0895         0.0395        0.055     7
4    2  0.425      0.3  0.095  ...          0.141         0.0775         0.12     8

[5 rows x 9 columns]

In [112]:
# 调整格子数据格式
df["Rings"] = pd.to_numeric(df["Rings"])
df["Rings"] = pd.cut(
    df.Rings, bins=[0, 10, 20, 30], labels=["small", "middle", "large"]
)
df.head()

   Sex Length Diameter Height  ... Shucked weight Viscera weight Shell weight  Rings
0    0   0.35    0.265   0.09  ...         0.0995         0.0485         0.07  small
1    1   0.53     0.42  0.135  ...         0.2565         0.1415         0.21  small
2    0   0.44    0.365  0.125  ...         0.2155          0.114        0.155  small
3    2   0.33    0.255   0.08  ...         0.0895         0.0395        0.055  small
4    2  0.425      0.3  0.095  ...          0.141         0.0775         0.12  small

[5 rows x 9 columns]

In [113]:
print(df.iloc[[3, 6, 12, 83]]["Rings"].values)
df.head()

['small', 'middle', 'small', 'middle']
Categories (3, object): ['small' < 'middle' < 'large']

   Sex Length Diameter Height  ... Shucked weight Viscera weight Shell weight  Rings
0    0   0.35    0.265   0.09  ...         0.0995         0.0485         0.07  small
1    1   0.53     0.42  0.135  ...         0.2565         0.1415         0.21  small
2    0   0.44    0.365  0.125  ...         0.2155          0.114        0.155  small
3    2   0.33    0.255   0.08  ...         0.0895         0.0395        0.055  small
4    2  0.425      0.3  0.095  ...          0.141         0.0775         0.12  small

[5 rows x 9 columns]

In [ ]:
# sklearn.model_selection.KFold(n_splits=3, shuffle=False, random_state=None)
# - n_splits : 默认 3；最小为 2，表示 K 折子集划分的 K 值。
# - shuffle : 默认 False; 当为 True 时，会对数据产生随机搅动。
# - random_state : 默认 None；随机数种子。

In [118]:
from sklearn.model_selection import KFold

kf = KFold(10, shuffle=True, random_state=50)

kf

KFold(n_splits=10, random_state=50, shuffle=True)

In [119]:
# 直接运行查看结果
for train_index, test_index in kf.split(df):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))

TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3759 TEST: 418
TRAIN: 3760 TEST: 417
TRAIN: 3760 TEST: 417
TRAIN: 3760 TEST: 417

In [127]:
# sklearn.model_selection.cross_val_score(estimator, X, y=None, groups=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch=‘2*n_jobs’)
# - estimator : 模型。
# - X : 特征组成的数组。
# - y : 目标值组成的数组。
# - cv : K 折数量。

In [132]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

features = df.iloc[:, 0:8]
target = df["Rings"]

model = KNeighborsClassifier()
# cross_val_score(model, X=df.iloc[:, 0:8], y=df["Rings"], cv=10)
cross_val_score(model, X=df.iloc[:, 0:8], y=df.iloc[:, -1], cv=10)

array([0.75837321, 0.72009569, 0.78229665, 0.72727273, 0.73684211,
       0.74162679, 0.76315789, 0.74580336, 0.76019185, 0.73621103])

In [138]:
# 同时使用多种模型，并且使用k折数据法，进行快速验证选取哪一个模型
# 7 种分类预测模型的表现都还不错，其中支持向量机、人工神经网络、随机森林等表现突出。此时，我们就可以先初选出这几种方法，然后通过调参得到更理想的结果。

"""加载分类器模块
"""
import numpy as np
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

"""各分类模型 10 折交叉验证函数
"""


def classifiers():
    """
    参数:无

    返回:
    scores -- 各分类模型 10 折交叉验证平均结果（列表）
    """
    models = [
        LogisticRegression(),
        KNeighborsClassifier(),
        SVC(),
        MLPClassifier(),
        DecisionTreeClassifier(),
        RandomForestClassifier(),
        AdaBoostClassifier(),
    ]
    scores = []

    for model in models:
        res = cross_val_score(model, X=df.iloc[:, 0:8], y=df.iloc[:, -1], cv=10)
        mean_score = np.mean(res)
        scores.append(mean_score)

    return scores


classifiers()

C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\91658\Miniconda3\envs\ml\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

[0.7601069383727468,
 0.7471871306782325,
 0.757236698679334,
 0.7680137229928975,
 0.6820637270088237,
 0.7649048225534404,
 0.7282870354434156]