In [16]:
import pandas as pd

dff = pd.read_csv("./GOOGL.csv")

dff.head(15)

         Date        Open        High  ...       Close   Adj Close    Volume
0    2005/1/3   98.798798  101.921921  ...  101.456459  101.456459  31656700
1    2005/1/4  100.800804  101.566566  ...   97.347351   97.347351  27484200
2    2005/1/5   96.821823   98.548546  ...   96.851852   96.851852  16456700
3    2005/1/6   97.637634   98.048050  ...   94.369370   94.369370  20753400
4    2005/1/7   95.415413   97.222221  ...   97.022018   97.022018  19306400
5   2005/1/10   97.347351   99.149147  ...   97.627625   97.627625  15064100
6   2005/1/11   97.907906   98.953957  ...   96.866867   96.866867  13903400
7   2005/1/12   97.262260   98.063065  ...   97.787788   97.787788  16339200
8   2005/1/13   97.787788   98.793793  ...   97.762764   97.762764  13685100
9   2005/1/14   98.098099  100.105103  ...  100.085083  100.085083  19261300
10  2005/1/18  100.585587  102.612610  ...  102.052055  102.052055  26318800
11  2005/1/19  102.427429  102.752754  ...   98.748749   98.748749  22492800
12  2005/1/20   96.346344   98.223221  ...   97.057060   97.057060  17985100
13  2005/1/21   97.367371   97.777779  ...   94.234238   94.234238  18498200
14  2005/1/24   94.439438   94.759758  ...   90.450447   90.450447  28017300

[15 rows x 7 columns]

In [103]:
# import datetime
# import numpy as np


# def date_to_datetime(date_str):
#     return datetime.datetime.strptime(date_str, "%Y/%m/%d")

# def calc_mean(lines,key):
#     mean_values = np.mean(lines, axis=0)
#     insert = np.insert(mean_values,0,key)
#     return insert


# def quarter_volume():
#     columns = dff.columns.tolist()
#     date_column = columns.index("Date")
#     data = np.array(dff.values)
#     # np.argsort([date_to_datetime(date) for date in data[:, date_column]])[::-1]  从大到小
#     sort_index = np.argsort([date_to_datetime(date) for date in data[:, date_column]])

#     # 遍历所有行的 date_column 列进行转换
#     # date_to_datetime(date) for date in data[:, date_column]
#     # np.argsort 从小到大排序后的索引数组
#     # sorted_data = data[[xxx]] #  np.array 可以根据索引重新排序
#     sorted_data = data[sort_index]
#     min_date = date_to_datetime(sorted_data[0][date_column])
#     max_date = date_to_datetime(sorted_data[-1][date_column])
#     new_data = []
#     d = []
#     prev_key = ""
#     key = ""
#     for line in sorted_data:
#         date = date_to_datetime(line[date_column])
#         year = date.year
#         month = date.month
#         if month <= 3:
#             key = f"{year}-第一季度"
#         elif month <= 6:
#             key = f"{year}-第二季度"
#         elif month <= 9:
#             key = f"{year}-第三季度"
#         else:
#             key = f"{year}-第四季度"
#         if prev_key != key:
#             if len(d) > 0:
#                 l = calc_mean(d,prev_key)
#                 new_data.append(l)
#             prev_key = key
#             d = []
#         l = np.delete(line.copy(),date_column)
#         d.append(l)
#     l = calc_mean(d,key)
#     new_data.append(l)
#     return pd.DataFrame(new_data, columns=dff.columns)  # 返回题目要求的 DataFrame


# quarter_volume()

         Date         Open         High  ...        Close    Adj Close        Volume
0   2005-第一季度    95.061947    96.312952  ...    94.747699    94.747699  2.301703e+07
1   2005-第二季度   121.146146   122.896256  ...   121.554523   121.554523  2.714345e+07
2   2005-第三季度   148.090590   149.723786  ...   148.214620   148.214620  1.617358e+07
3   2005-第四季度   190.464512   192.353543  ...   190.283220   190.283220  1.913668e+07
4   2006-第一季度   195.894927   198.766912  ...   195.342278   195.342278  2.911046e+07
5   2006-第二季度   198.767022   201.024517  ...   198.328011   198.328011  1.597237e+07
6   2006-第三季度   196.440806   198.137106  ...   196.108570   196.108570  1.129168e+07
7   2006-第四季度   233.356134   235.595436  ...   233.248963   233.248963  1.169042e+07
8   2007-第一季度   235.389734   237.606131  ...   235.094192   235.094192  1.168064e+07
9   2007-第二季度   243.560783   245.710551  ...   243.669384   243.669384  1.019890e+07
10  2007-第三季度   263.196609   265.527114  ...   263.567455   263.567455  8.713303e+06
11  2007-第四季度   334.470251   338.446728  ...   334.128036   334.128036  1.286958e+07
12  2008-第一季度   261.312953   265.466613  ...   260.347317   260.347317  1.574125e+07
13  2008-第二季度   272.035708   275.528887  ...   271.549752   271.549752  1.065997e+07
14  2008-第三季度   239.450311   243.169966  ...   238.513435   238.513435  9.583450e+06
15  2008-第四季度   161.990584   166.782016  ...   161.522068   161.522068  1.468325e+07
16  2009-第一季度   165.781600   169.294868  ...   166.133264   166.133264  1.098706e+07
17  2009-第二季度   200.205841   202.672593  ...   200.636986   200.636986  6.828963e+06
18  2009-第三季度   227.370026   229.447886  ...   227.655781   227.655781  5.395661e+06
19  2009-第四季度   282.630051   284.662787  ...   282.999327   282.999327  5.016834e+06
20  2010-第一季度   279.739083   282.247987  ...   279.460443   279.460443  7.366652e+06
21  2010-第二季度   257.667111   260.146018  ...   256.632425   256.632425  6.802200e+06
22  2010-第三季度   241.017893   243.484733  ...   241.353932   241.353932  5.677581e+06
23  2010-第四季度   295.635869   297.474192  ...   295.226320   295.226320  5.621669e+06
24  2011-第一季度   302.333300   304.483838  ...   302.082971   302.082971  5.220290e+06
25  2011-第二季度   264.840473   266.516358  ...   264.324562   264.324562  5.540270e+06
26  2011-第三季度   275.715245   279.257772  ...   275.547970   275.547970  7.694152e+06
27  2011-第四季度   297.016378   300.023673  ...   297.553109   297.553109  6.106960e+06
28  2012-第一季度   308.563159   310.769641  ...   308.580355   308.580355  5.424760e+06
29  2012-第二季度   299.952730   302.519661  ...   299.428636   299.428636  5.202846e+06
30  2012-第三季度   327.591321   331.051447  ...   328.921143   328.921143  5.027535e+06
31  2012-第四季度   351.016903   353.757789  ...   350.233457   350.233457  5.161669e+06
32  2013-第一季度   389.324073   392.331830  ...   389.644227   389.644227  4.705058e+06
33  2013-第二季度   424.663492   428.198512  ...   425.050909   425.050909  4.731155e+06
34  2013-第三季度   444.392595   446.835508  ...   444.100899   444.100899  3.679270e+06
35  2013-第四季度   507.321228   511.369494  ...   508.152214   508.152214  3.600228e+06
36  2014-第一季度   586.777350   590.087713  ...   585.081555   585.081555  4.543408e+06
37  2014-第二季度   552.681386   557.170035  ...   552.274304   552.274304  2.412860e+06
38  2014-第三季度   589.540628   593.085623  ...   589.367034   589.367034  1.610736e+06
39  2014-第四季度   547.420157   551.588278  ...   546.313908   546.313908  2.182600e+06
40  2015-第一季度   541.537213   546.473608  ...   541.776556   541.776556  2.233166e+06
41  2015-第二季度   549.764601   553.551906  ...   549.368095   549.368095  1.765917e+06
42  2015-第三季度   644.527187   651.529530  ...   643.884216   643.884216  2.611248e+06
43  2015-第四季度   739.572033   746.378597  ...   740.154374   740.154374  2.053736e+06
44  2016-第一季度   737.272462   745.072133  ...   736.288523   736.288523  2.659423e+06
45  2016-第二季度   734.562967   739.614059  ...   734.012033   734.012033  1.914633e+06
46  2016-第三季度   780.932186   785.743126  ...   782.192970   782.192970  1.453325e+06
47  2016-第四季度   801.189842   806.646983  ...   799.666824   799.666824  1.873462e+06
48  2017-第一季度   840.688549   844.655807  ...   840.975809   840.975809  1.577473e+06
49  2017-第二季度   935.238729   941.148253  ...   935.503019   935.503019  1.716033e+06
50  2017-第三季度   948.157938   954.277299  ...   948.566034   948.566034  1.656808e+06
51  2017-第四季度  1032.165557  1039.191746  ...  1032.479208  1032.479208  1.515560e+06

[52 rows x 7 columns]

In [107]:

def quarter_volume1():
    # 读取数据，并且以第一列作为索引，不要默认的 1、2、3.....了
    df = pd.read_csv("GOOGL.csv", index_col=0)
    df.index = pd.to_datetime(df.index)
    df = df.resample('Q').agg({"Open": 'mean', "High": 'mean', "Low": 'mean',
                               "Close": 'mean', "Adj Close": 'mean', "Volume": 'sum'})
    # 按 Volume 排序
    df = df.sort_values(by='Volume', ascending=False)
    return df

In [108]:
quarter_volume1()

DatetimeIndex(['2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06',
               '2005-01-07', '2005-01-10', '2005-01-11', '2005-01-12',
               '2005-01-13', '2005-01-14',
               ...
               '2017-12-15', '2017-12-18', '2017-12-19', '2017-12-20',
               '2017-12-21', '2017-12-22', '2017-12-26', '2017-12-27',
               '2017-12-28', '2017-12-29'],
              dtype='datetime64[ns]', name='Date', length=3272, freq=None)

C:\Users\91658\AppData\Local\Temp\ipykernel_85524\1620123924.py:5: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  df = df.resample('Q').agg({"Open": 'mean', "High": 'mean', "Low": 'mean',

                   Open         High  ...    Adj Close      Volume
Date                                  ...
2006-03-31   195.894927   198.766912  ...   195.342278  1804848300
2005-06-30   121.146146   122.896256  ...   121.554523  1737181000
2005-03-31    95.061947    96.312952  ...    94.747699  1404038900
2005-12-31   190.464512   192.353543  ...   190.283220  1205611000
2005-09-30   148.090590   149.723786  ...   148.214620  1035109100
2006-06-30   198.767022   201.024517  ...   198.328011  1006259000
2008-03-31   261.312953   265.466613  ...   260.347317   960216300
2008-12-31   161.990584   166.782016  ...   161.522068   939728200
2007-12-31   334.470251   338.446728  ...   334.128036   823653100
2006-12-31   233.356134   235.595436  ...   233.248963   736496600
2007-03-31   235.389734   237.606131  ...   235.094192   712518900
2006-09-30   196.440806   198.137106  ...   196.108570   711375600
2008-06-30   272.035708   275.528887  ...   271.549752   682238300
2009-03-31   165.781600   169.294868  ...   166.133264   670210600
2007-06-30   243.560783   245.710551  ...   243.669384   642530900
2008-09-30   239.450311   243.169966  ...   238.513435   613340800
2007-09-30   263.196609   265.527114  ...   263.567455   548938100
2011-09-30   275.715245   279.257772  ...   275.547970   492425700
2010-03-31   279.739083   282.247987  ...   279.460443   449365800
2009-06-30   200.205841   202.672593  ...   200.636986   430224700
2010-06-30   257.667111   260.146018  ...   256.632425   428538600
2011-12-31   297.016378   300.023673  ...   297.553109   384738500
2010-09-30   241.017893   243.484733  ...   241.353932   363365200
2010-12-31   295.635869   297.474192  ...   295.226320   359786800
2011-06-30   264.840473   266.516358  ...   264.324562   349037000
2009-09-30   227.370026   229.447886  ...   227.655781   345322300
2012-03-31   308.563159   310.769641  ...   308.580355   336335100
2012-06-30   299.952730   302.519661  ...   299.428636   327779300
2011-03-31   302.333300   304.483838  ...   302.082971   323658000
2009-12-31   282.630051   284.662787  ...   282.999327   321077400
2012-12-31   351.016903   353.757789  ...   350.233457   320023500
2012-09-30   327.591321   331.051447  ...   328.921143   316734700
2013-06-30   424.663492   428.198512  ...   425.050909   302793900
2013-03-31   389.324073   392.331830  ...   389.644227   282303500
2014-03-31   586.777350   590.087713  ...   585.081555   277147900
2013-09-30   444.392595   446.835508  ...   444.100899   235473300
2013-12-31   507.321228   511.369494  ...   508.152214   230414600
2015-09-30   644.527187   651.529530  ...   643.884216   167119900
2016-03-31   737.272462   745.072133  ...   736.288523   162224800
2014-06-30   552.681386   557.170035  ...   552.274304   152010200
2014-12-31   547.420157   551.588278  ...   546.313908   139686400
2015-03-31   541.537213   546.473608  ...   541.776556   136223100
2015-12-31   739.572033   746.378597  ...   740.154374   131439100
2016-06-30   734.562967   739.614059  ...   734.012033   122536500
2016-12-31   801.189842   806.646983  ...   799.666824   118028100
2015-06-30   549.764601   553.551906  ...   549.368095   111252800
2017-06-30   935.238729   941.148253  ...   935.503019   108110100
2017-09-30   948.157938   954.277299  ...   948.566034   104378900
2014-09-30   589.540628   593.085623  ...   589.367034   103087100
2017-03-31   840.688549   844.655807  ...   840.975809    97803300
2017-12-31  1032.165557  1039.191746  ...  1032.479208    95480300
2016-09-30   780.932186   785.743126  ...   782.192970    93012800

[52 rows x 6 columns]